AWSTemplateFormatVersion: '2010-09-09'
Description: None
Resources:
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0a887e401f7654935
      InstanceType: t2.micro
      KeyName: mytestkey
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum update -y aws-cfn-bootstrap # good practice - always do this.
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2 --configsets nginx --region ${AWS::Region}
            yum -y update
